-- ==========================
-- INSERT REFERENCE TABLES
-- ==========================

-- CURRENCY
INSERT INTO CURRENCY (CURRENCY_CODE, DECIMAL_PLACES, DESCRIPTION)
SELECT 'ZAR', 2, 'South African Rand'
    WHERE NOT EXISTS (SELECT 1 FROM CURRENCY WHERE CURRENCY_CODE = 'ZAR');

INSERT INTO CURRENCY (CURRENCY_CODE, DECIMAL_PLACES, DESCRIPTION)
SELECT 'USD', 2, 'US Dollar'
    WHERE NOT EXISTS (SELECT 1 FROM CURRENCY WHERE CURRENCY_CODE = 'USD');

INSERT INTO CURRENCY (CURRENCY_CODE, DECIMAL_PLACES, DESCRIPTION)
SELECT 'EUR', 2, 'Euro'
    WHERE NOT EXISTS (SELECT 1 FROM CURRENCY WHERE CURRENCY_CODE = 'EUR');


-- ACCOUNT TYPE
INSERT INTO ACCOUNT_TYPE (ACCOUNT_TYPE_CODE, DESCRIPTION, TRANSACTIONAL)
SELECT 'TRAN', 'Transactional Account', TRUE
    WHERE NOT EXISTS (SELECT 1 FROM ACCOUNT_TYPE WHERE ACCOUNT_TYPE_CODE = 'TRAN');

INSERT INTO ACCOUNT_TYPE (ACCOUNT_TYPE_CODE, DESCRIPTION, TRANSACTIONAL)
SELECT 'CCY', 'Currency Account', FALSE
    WHERE NOT EXISTS (SELECT 1 FROM ACCOUNT_TYPE WHERE ACCOUNT_TYPE_CODE = 'CCY');


-- CURRENCY CONVERSION RATE
INSERT INTO CURRENCY_CONVERSION_RATE (CURRENCY_CODE, CONVERSION_INDICATOR, RATE)
SELECT 'USD', '*', 18.50
    WHERE NOT EXISTS (SELECT 1 FROM CURRENCY_CONVERSION_RATE WHERE CURRENCY_CODE = 'USD');

INSERT INTO CURRENCY_CONVERSION_RATE (CURRENCY_CODE, CONVERSION_INDICATOR, RATE)
SELECT 'EUR', '*', 20.00
    WHERE NOT EXISTS (SELECT 1 FROM CURRENCY_CONVERSION_RATE WHERE CURRENCY_CODE = 'EUR');



-- ==========================
-- CLIENT AND ACCOUNTS
-- ==========================

-- CLIENT
INSERT INTO CLIENT (ID, TITLE, NAME, SURNAME)
SELECT 1, 'Mr', 'John', 'Doe'
    WHERE NOT EXISTS (SELECT 1 FROM CLIENT WHERE ID = 1);


-- CLIENT ACCOUNT
INSERT INTO CLIENT_ACCOUNT (
    CLIENT_ACCOUNT_NUMBER, CLIENT_ID, ACCOUNT_TYPE_CODE, CURRENCY_CODE, DISPLAY_BALANCE
)
SELECT 'TX12345', 1, 'TRAN', 'ZAR', 2000.0
    WHERE NOT EXISTS (SELECT 1 FROM CLIENT_ACCOUNT WHERE CLIENT_ACCOUNT_NUMBER = 'TX12345');

INSERT INTO CLIENT_ACCOUNT (
    CLIENT_ACCOUNT_NUMBER, CLIENT_ID, ACCOUNT_TYPE_CODE, CURRENCY_CODE, DISPLAY_BALANCE
)
SELECT 'FX12345', 1, 'CCY', 'USD', 100.0
    WHERE NOT EXISTS (SELECT 1 FROM CLIENT_ACCOUNT WHERE CLIENT_ACCOUNT_NUMBER = 'FX12345');

INSERT INTO CLIENT_ACCOUNT (
    CLIENT_ACCOUNT_NUMBER, CLIENT_ID, ACCOUNT_TYPE_CODE, CURRENCY_CODE, DISPLAY_BALANCE
)
SELECT 'FXEUR123', 1, 'CCY', 'EUR', 300.0
    WHERE NOT EXISTS (SELECT 1 FROM CLIENT_ACCOUNT WHERE CLIENT_ACCOUNT_NUMBER = 'FXEUR123');



-- ==========================
-- ATM AND DENOMINATION
-- ==========================

-- ATM
INSERT INTO ATM (ID, LOCATION, ACTIVE)
SELECT 1, 'Test Location', TRUE
    WHERE NOT EXISTS (SELECT 1 FROM ATM WHERE ID = 1);

-- DENOMINATION
INSERT INTO DENOMINATION (DENOMINATION_ID, DENOMINATION_VALUE)
SELECT 1, 200
    WHERE NOT EXISTS (SELECT 1 FROM DENOMINATION WHERE DENOMINATION_ID = 1);

INSERT INTO DENOMINATION (DENOMINATION_ID, DENOMINATION_VALUE)
SELECT 2, 100
    WHERE NOT EXISTS (SELECT 1 FROM DENOMINATION WHERE DENOMINATION_ID = 2);

INSERT INTO DENOMINATION (DENOMINATION_ID, DENOMINATION_VALUE)
SELECT 3, 50
    WHERE NOT EXISTS (SELECT 1 FROM DENOMINATION WHERE DENOMINATION_ID = 3);


-- ATM ALLOCATION
INSERT INTO ATM_ALLOCATION (ATM_ID, DENOMINATION_ID, COUNT)
SELECT 1, 1, 10
    WHERE NOT EXISTS (SELECT 1 FROM ATM_ALLOCATION WHERE ATM_ID = 1 AND DENOMINATION_ID = 1);

INSERT INTO ATM_ALLOCATION (ATM_ID, DENOMINATION_ID, COUNT)
SELECT 1, 2, 10
    WHERE NOT EXISTS (SELECT 1 FROM ATM_ALLOCATION WHERE ATM_ID = 1 AND DENOMINATION_ID = 2);

INSERT INTO ATM_ALLOCATION (ATM_ID, DENOMINATION_ID, COUNT)
SELECT 1, 3, 10
    WHERE NOT EXISTS (SELECT 1 FROM ATM_ALLOCATION WHERE ATM_ID = 1 AND DENOMINATION_ID = 3);
