SELECT
    C.ID AS CLIENT_ID,
    C.SURNAME,
    A.CLIENT_ACCOUNT_NUMBER,
    A.DISPLAY_BALANCE
FROM CLIENT C
         JOIN CLIENT_ACCOUNT A ON C.ID = A.CLIENT_ID
         JOIN ACCOUNT_TYPE T ON A.ACCOUNT_TYPE_CODE = T.ACCOUNT_TYPE_CODE
WHERE T.TRANSACTIONAL = TRUE
  AND A.DISPLAY_BALANCE = (
    SELECT MAX(A2.DISPLAY_BALANCE)
    FROM CLIENT_ACCOUNT A2
             JOIN ACCOUNT_TYPE T2 ON A2.ACCOUNT_TYPE_CODE = T2.ACCOUNT_TYPE_CODE
    WHERE A2.CLIENT_ID = C.ID AND T2.TRANSACTIONAL = TRUE
);
